# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyfivem < Formula
  desc ""
  homepage ""
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itschip/lazyfivem/releases/download/0.0.2/lazyfivem_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "585a905f8dbf9d6f2b98bbc6b3351012ceeeb76e91736f842e104ff9ee2de4af"

      def install
        bin.install "lazyfivem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itschip/lazyfivem/releases/download/0.0.2/lazyfivem_0.0.2_Darwin_arm64.tar.gz"
      sha256 "c014a764fc4a175bf70072a5bbb6a2c0a1d03fba2100ce889b539ef75f407835"

      def install
        bin.install "lazyfivem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/itschip/lazyfivem/releases/download/0.0.2/lazyfivem_0.0.2_Linux_armv6.tar.gz"
      sha256 "f657160fcf1915abf17834b5d9d8727bfba3b67e24bdc4a167dd1587c1355924"

      def install
        bin.install "lazyfivem"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/itschip/lazyfivem/releases/download/0.0.2/lazyfivem_0.0.2_Linux_x86_64.tar.gz"
      sha256 "1437ba32f47c24574f2b384e0c25fcefa526a2d6d46dd38ce198d96117ce4331"

      def install
        bin.install "lazyfivem"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itschip/lazyfivem/releases/download/0.0.2/lazyfivem_0.0.2_Linux_arm64.tar.gz"
      sha256 "18ba41d6d829ada86410a082b17be9395780d6fbdb3ffc5e621f2f0b29b01012"

      def install
        bin.install "lazyfivem"
      end
    end
  end
end
