# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyfivem < Formula
  desc ""
  homepage ""
  version "0.0.111"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/itschip/lazyfivem/releases/download/0.0.111/lazyfivem_0.0.111_Darwin_arm64.tar.gz"
      sha256 "314d0ef0cac01c66fe6f99c330ca69f3038fc6571ef926037a47a5f34e982f47"

      def install
        bin.install "lazyfivem"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/itschip/lazyfivem/releases/download/0.0.111/lazyfivem_0.0.111_Darwin_x86_64.tar.gz"
      sha256 "5ae55ef1ef418a4a8f35f4fd88867cec274cd8b9ae4837c7d85cd838d84b9706"

      def install
        bin.install "lazyfivem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itschip/lazyfivem/releases/download/0.0.111/lazyfivem_0.0.111_Linux_arm64.tar.gz"
      sha256 "717d8db8596bd70680af5cc812d176dbf9b6f7cf79730c024a286b9aa5cec519"

      def install
        bin.install "lazyfivem"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/itschip/lazyfivem/releases/download/0.0.111/lazyfivem_0.0.111_Linux_armv6.tar.gz"
      sha256 "d584b0aef4248f6a8f897562a5def58ddbc3adb17f95adf17e4025d66767debe"

      def install
        bin.install "lazyfivem"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/itschip/lazyfivem/releases/download/0.0.111/lazyfivem_0.0.111_Linux_x86_64.tar.gz"
      sha256 "e2fd60bd5953fe966cdd1eb076a40cde8c0bfe7af81e4cb673b4a7eca2b980fd"

      def install
        bin.install "lazyfivem"
      end
    end
  end
end
