# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyfivem < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/itschip/lazyfivem/releases/download/1.0.0/lazyfivem_1.0.0_Darwin_arm64.tar.gz"
      sha256 "92a53c3db7fabe4164f11462b2b9db0afe8aacf8dde003289040bb00c7aefa25"

      def install
        bin.install "lazyfivem"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/itschip/lazyfivem/releases/download/1.0.0/lazyfivem_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "521fb914e77abc3a12083038fba577f20a6b83acd4f1859c45784bdcdc508c1d"

      def install
        bin.install "lazyfivem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itschip/lazyfivem/releases/download/1.0.0/lazyfivem_1.0.0_Linux_arm64.tar.gz"
      sha256 "d796586ba6ad2b39f45c9a381a88ca23b5021659811e5e55a98e53ea2369d386"

      def install
        bin.install "lazyfivem"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/itschip/lazyfivem/releases/download/1.0.0/lazyfivem_1.0.0_Linux_x86_64.tar.gz"
      sha256 "92e1a2ebdb90c184f7767d298cc281dc1c52d36cecd6f153e85c7a9e992e5bc1"

      def install
        bin.install "lazyfivem"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/itschip/lazyfivem/releases/download/1.0.0/lazyfivem_1.0.0_Linux_armv6.tar.gz"
      sha256 "d6226ad1244ba9a63423df42ced2c0f2dd886db32af203a32f2028df837f20d5"

      def install
        bin.install "lazyfivem"
      end
    end
  end
end
